# Generated by Django 3.0.3 on 2020-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_test',
            name='my_field_name',
            field=models.CharField(default='Def', help_text='Enter field documentation', max_length=20),
        ),
    ]
