# Generated by Django 3.0.3 on 2020-05-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0002_db_test_my_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_titel', models.CharField(default='Note_Titel', help_text='N_Titel', max_length=20, verbose_name='Note Titlel')),
                ('pub_date_n', models.DateField(verbose_name='Pub date')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_titel', models.CharField(default='Sheet_Titel', help_text='M_Titel', max_length=20, verbose_name='Main Titel')),
                ('pub_date', models.DateField(verbose_name='Pub date')),
            ],
        ),
        migrations.DeleteModel(
            name='Db_test',
        ),
        migrations.AddField(
            model_name='note',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Todo_List.Sheet'),
        ),
    ]
