# Generated by Django 3.0.3 on 2020-06-02 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0010_auto_20200603_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dead_line',
            field=models.DateField(default=datetime.datetime(2020, 6, 2, 23, 45, 18, 515847, tzinfo=utc), verbose_name='Dead Line'),
        ),
        migrations.AlterField(
            model_name='note',
            name='real_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 2, 23, 45, 18, 515847, tzinfo=utc), verbose_name='Real date'),
        ),
        migrations.AlterField(
            model_name='note_buffer',
            name='buf_d_line',
            field=models.DateField(verbose_name='Dead Line'),
        ),
        migrations.AlterField(
            model_name='note_buffer',
            name='buf_real_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 2, 23, 45, 18, 516844, tzinfo=utc), verbose_name='Real date'),
        ),
    ]
