# Generated by Django 3.0.3 on 2020-06-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0011_auto_20200603_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dead_line',
            field=models.DateField(verbose_name='Dead Line'),
        ),
        migrations.AlterField(
            model_name='note',
            name='real_date',
            field=models.DateField(verbose_name='Real date'),
        ),
        migrations.AlterField(
            model_name='note_buffer',
            name='buf_real_date',
            field=models.DateField(verbose_name='Real date'),
        ),
    ]
