# Generated by Django 3.0.3 on 2020-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0014_json_sheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='json_sheet',
            old_name='json_title',
            new_name='json_path',
        ),
        migrations.AlterField(
            model_name='json_sheet',
            name='json_file',
            field=models.FileField(upload_to=models.CharField(default='JSON_Title', help_text='JSON', max_length=20, verbose_name='JSON')),
        ),
    ]
