# Generated by Django 3.0.3 on 2020-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0016_auto_20200604_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSON_sheet',
        ),
        migrations.AlterField(
            model_name='note',
            name='task_text',
            field=models.CharField(default='Task Text', help_text='Task', max_length=3000, verbose_name='____Task Text'),
        ),
    ]
