# Generated by Django 3.0.3 on 2020-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0017_auto_20200606_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_buffer',
            name='buf_task',
            field=models.CharField(default='Task_Text', help_text='Task', max_length=3000, verbose_name='____Task Text'),
        ),
    ]
