# Generated by Django 3.0.3 on 2020-06-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0018_auto_20200606_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='color',
            field=models.CharField(default='Sheet_Color', help_text='Color Sheet', max_length=25, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_titel',
            field=models.CharField(default='Sheet_Title', help_text='M_Title', max_length=20, verbose_name='Main Title'),
        ),
    ]
