# Generated by Django 3.0.3 on 2020-06-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List', '0019_auto_20200606_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='sheet_titel',
            new_name='sheet_title',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(default='Note_Title', help_text='Title', max_length=20, verbose_name='Note Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='task_text',
            field=models.CharField(default='Task Text', help_text='Task', max_length=3000, verbose_name='Note Task Text'),
        ),
        migrations.AlterField(
            model_name='note_buffer',
            name='buf_task',
            field=models.CharField(default='Buffer_Task_Text', help_text='Buffer Task', max_length=3000, verbose_name='Buffer Task Text'),
        ),
        migrations.AlterField(
            model_name='note_buffer',
            name='buf_title',
            field=models.CharField(default='Buffer_Title', help_text='Buf_Title', max_length=20, verbose_name='Buffer Title'),
        ),
    ]
